export const SET_PLAYING = 'SET_PLAYING'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_PLAY_LIST = 'SET_PLAY_LIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_SONG_DURATION = 'SET_SONG_DURATION'

export const SET_SONG_IMAGE = 'SET_SONG_IMAGE'
